version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: moment-canvas-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234   # 비밀번호 설정
      MYSQL_DATABASE: moment_canvas # DB 이름
      MYSQL_TZ: Asia/Seoul
    ports:
      - "3307:3306" # 내 컴퓨터의 3307 포트를 컨테이너의 3306에 연결
    volumes:
      - ./db/data:/var/lib/mysql  # 프로젝트 폴더 db/data에 데이터를 저장 (데이터 보존)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # Redis
  redis:
    image: redis:latest
    container_name: moment-canvas-redis
    restart: always
    ports:
      - "6379:6379"      # 기본 포트 6379 개방
    volumes:
      - ./redis/data:/data  # Redis 데이터도 날아가지 않게 로컬에 저장
    command: redis-server --requirepass 1234 --appendonly yes # 비밀번호 설정 및 지속성 설정